services:
  db:
    image: postgres:16
    container_name: service-lab-db
    environment:
      POSTGRES_DB: service_lab
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab1234
    ports:
      - "5433:5432"
    volumes:
      - service-lab-db-data:/var/lib/postgresql/data

volumes:
  service-lab-db-data: